### ISSUE TITLE
hw93 feedback

### ISSUE THREAD

**Issue by DavidHolmes0** [Rachel-W3/WuWongClan_Wong-R_Wu-J#1]
## statement of problem
Cleaning up this section is likely to help you significantly .
This needs re-wording, since its current form tells the reader that you are planning to return a value like "yes", but then says you will return "true or false".
The fix is to start with language like "Returns the Boolean value of the statement...

The concept of "is this path the shortest possible path?" should await v*n*, for *n* != 1

## recursive abstraction
Figure out what you meant by "forward". I expect that once you do that, you can remove that complicated concept, resulting in *much* simpler programming problem.

## English or pseudocode description of algorithm
"proceed to the next step" sounds  like [inappropriate language](http://www.davidmholmes.net/Stuy/ap/notes.html#2018-02-27). What do you really mean?

**Comment by Rachel-W3** [comment]
Thank you for the input Mr. Holmes. I had trouble for the past few days figuring out what we meant by "forward" and how we'll be able to backtrack if we're putting walls behind us, because I wasn't sure how we'd determine whether the explorer would encounter an intersection or not -- I guess I was thinking too much like a human. But Matthew's comment on the pseudocode gave me the idea to check if every direction is a wall or not.
